package de.htwg.blackjack.entities.impl;


public enum Card {

    HERZZWEI(2), HERZDREI(3), HERZVIER(4), HERZFUENF(5), HERZSECHS(6), HERZSIEBEN(7), HERZACHT(8),
    HERZNEUN(9), HERZZEHN(10), HERZBUBE(10), HERZDAME(10), HERZKOENIG(10), HERZASS(11),
    KARODREI(3), KAROVIER(4), KAROFUENF(5), KAROSECHS(6), KAROSIEBEN(7), KAROACHT(8),
    KARONEUN(9), KAROZEHN(10), KAROBUBE(10), KARODAME(10), KAROKOENIG(10), KAROASS(11),
    PIKZWEI(2), PIKDREI(3), PIKVIER(4), PIKFUENF(5), PIKSECHS(6), PIKSIEBEN(7), PIKACHT(8),
    PIKNEUN(9), PIKZEHN(10), PIKBUBE(10), PIKDAME(10), PIKKOENIG(10), PIKASS(11),
    KREUZZWEI(2), KREUZDREI(3), KREUZVIER(4), KREUZFUENF(5), KREUZSECHS(6), KREUZSIEBEN(7), KREUZACHT(8),
    KREUZNEUN(9), KREUZZEHN(10), KREUZBUBE(10), KREUZDAME(10), KREUZKOENIG(10), KREUZASS(11);

    private final int cardValue;

    private Card(int cardValue) {
        this.cardValue = cardValue;
    }
    
    public int getCardValue() {
        return cardValue;
    }
}